/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    typeData1
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_Jni_typeData1
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jni
 * Method:    typeData2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jni_typeData2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Jni
 * Method:    typeData3
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Jni_typeData3
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
