/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    hello_implicit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Jni_hello_1implicit
  (JNIEnv *, jclass);

/*
 * Class:     Jni
 * Method:    hello_explicit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Jni_hello_1explicit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
